routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\JoinController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RelationController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::group(
    [
        'prefix' => 'store',
    ], function () {

        Route::resource('product', ProductController::class);

         Route::resource('category', CategoryController::class); 
        

        Route::resource('roles', RoleController::class);

        Route::resource('uesrs', UserController::class);

    });

Route::get('/', function () {
    return view('welcome');
});

Route::get('/join', [JoinController::class, 'show']);

Route::get('/relation', [RelationController::class, 'index'])->name('relation');

Route::get('about', [AboutController::class, 'about'])->name('about');

Route::get('contact', [AboutController::class, 'contact'])->name('contact');

Route::get('import-form', [ProductController::class, 'importForm'])->name('importForm');

Route::post('import',[ProductController::class,'import'])->name('import');

Route::get('export', [ProductController::class, 'export'])->name('export'); 

Route::get('categoryexport', [CategoryController::class, 'export'])->name('categoryexport'); 

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = "products";

    protected $fillable = [
        'Product_name', 'Product_description', 'Product_image', 'Product_code'
    ];
    

    public function category()
    {
      return $this->belongsToMany(Category::class,'category_product');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Exports\ProductExport;
use App\Imports\ProductImport;
use App\Models\Category;
use App\Models\Product;
use App\Repositories\product\ProductRepositories;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class ProductController extends Controller
{
    public $ProductRepositories;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(ProductRepositories $ProductRepositories)
    {
        $this->ProductRepositories = $ProductRepositories;
        $this->Middleware('auth');
    }

    public function index(Request $request)
    {
        $data = $this->ProductRepositories->all();

        return view('product.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        return view('home', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $product = Product::create([
            'Product_name' => $request->Product_name,
            'Product_description' => $request->Product_description,
            'Product_image' => $request->Product_image,
            'Product_code' => $request->Product_code,
        ]);

        $product->category()->attach($request->Category);

        return redirect()->route('product.index')->with('success', 'product added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::all();
        return view('product.show', compact('category'), ['product' => Product::findOrFail($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $category = Category::all();
        return view('product.edit', compact('product', 'category'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $product = Product::find($id);

        $product->Product_name = $request->Product_name;
        $product->Product_description = $request->Product_description;
        $product->Product_code = $request->Product_code;
        $product->category()->sync($request->category);
        $product->save();
        return redirect()->route('product.index')->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();

        echo ("User Record deleted successfully.");
        return redirect()->route('product.index');
    }

    public function export()
    {
        return Excel::download(new ProductExport, 'product.xlsx');
    }

    public function importForm()
    {
        return view('import-form');
    }
    public function import(Request $request)
    {
        Excel::import(new ProductImport, request()->file('file'));
        return back()->with('status', 'Import successfully done');
    }

}

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="{{ route('product.update', $product->id) }}" method="POST" id="regform"
            enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="hidden" name="id" value="{{ $product->id }}">
            <div class="form-group">
                <label for="name">Product Name</label>
                <input type="text" name="Product_name" value="{{ $product->Product_name }}" class="form-control 
                                                                @error('Product_name') is-invalid @enderror ">
                @error('Product_name')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="description">Product Description</label>
                <input type="text" name="Product_description" value="{{ $product->Product_description }}" class="form-control 
                                                                @error('Product_description') is-invalid @enderror ">
                @error('Product_description')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="image">Upload Image</label>
                <input type="file" name="Product_image" value="{{ $product->Product_image }}" class="form-control
                                                                @error('Product_image') is-invalid @enderror ">
                @error('Product_image')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="description">Product code</label>
                <input type="text" name="Product_code" value="{{ $product->Product_code }}" class="form-control
                                                                @error('Product_code') is-invalid @enderror ">
                @error('Product_code')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <select class="form-control category" name="category[]" multiple="multiple">
                    @foreach ($category as $item)
                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                    @endforeach

                </select>
            </div>
            <div>
                <input type="submit" value="Update" class="btn btn-danger btn-block">
            </div>
        </form>
    </div>
@endsection

@section('script')
    @php
    $category_ids = [];
    @endphp

    @foreach ($product->category as $item)
        @php
            array_push($category_ids, $item->id);
        @endphp
    @endforeach

    <script>
        $(document).ready(function() {
            $('.category').select2();
            data = [];
            data = <?php echo json_encode($category_ids); ?>;
            $('.category').val(data);
            $('.category').trigger('change');
        });
    </script>

@endsection

resources/views/product/index.blade.php
@extends('layouts.master')

@section('content')
    <div>
        @hasanyrole('create|admin')
        <a class="btn btn-primary rounded-pill" href="{{ route('product.create') }}"> Create New product</a>
        @endhasanyrole
    </div><br>

    <table class="table" id="product_table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">PRODUCT_NAME</th>
                <th scope="col">PRODUCT_DESCRIPTION</th>
                <th scope="col">PRODUCT_IMAGE</th>
                <th scope="col">PRODUCT_CODE</th>
                <th scope="col">OPERATION</th>
            </tr>
        </thead>


        <tbody>
            @foreach ($products as $product)
                <tr>
                    <td scope="col">{{ $product->id }}</td>
                    <td scope="col">{{ $product->Product_name }}</td>
                    <td scope="col">{{ $product->Product_description }}</td>
                    <td scope="col">{{ $product->Product_image }}</td>
                    <td scope="col">{{ $product->Product_code }}</td>
                    <td scope="col">
                        <form action="{{ route('product.destroy', $product->id) }}" method="POST"
                            onsubmit="return confirm('Are you sure want to delete it')">
                            @hasanyrole('delete|admin')
                            <a class="btn btn-info rounded-pill" href="{{ route('product.edit', $product->id) }}">EDIT</a>
                            @endhasanyrole

                            <a class="btn btn-warning rounded-pill"
                                href="{{ route('product.show', $product->id) }}">SHOW</a>

                            @csrf
                            @method('DELETE')
                            @hasanyrole('delete|admin')
                            <button type="submit" class="btn btn-danger rounded-pill" id="delete">DELETE</button>
                            @endhasanyrole

                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <script type="text/javascript">
        $('#product_table').DataTable({

        });
    </script>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content') 
    <div class="container">
        <form>
            <div class="form-group">
                <label for="name">Product Name</label>
                <input type="text"  value="{{$product['Product_name']}}" class="form-control">
            </div>
            <div class="form-group">
                <label for="name">Product Description</label>
                <input type="text" value="{{$product['Product_description']}}" class="form-control">
            </div>
            <div class="form-group">
                <label for="name">Product Code</label>
                <input type="text"  value="{{$product['Product_code']}}" class="form-control">
            </div>

            <div class="form-group">
                <label for="name">Product Image</label>
                <input type="text"  value="{{$product['Product_image']}}" class="form-control">
            </div>

            <div class="form-group">
                <label for="name">Category_Name</label>   
                @foreach ($category as $item)
                <input type="text"  value="{{$item['name']}}" class="form-control">
                    @endforeach
            </div>
        </form>
@endsection