routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\JoinController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RelationController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::group(
    [
        'prefix' => 'store',
    ], function () {

        Route::resource('product', ProductController::class);

         Route::resource('category', CategoryController::class); 
        

        Route::resource('roles', RoleController::class);

        Route::resource('uesrs', UserController::class);

    });

Route::get('/', function () {
    return view('welcome');
});

Route::get('/join', [JoinController::class, 'show']);

Route::get('/relation', [RelationController::class, 'index'])->name('relation');

Route::get('about', [AboutController::class, 'about'])->name('about');

Route::get('contact', [AboutController::class, 'contact'])->name('contact');

Route::get('import-form', [ProductController::class, 'importForm'])->name('importForm');

Route::post('import',[ProductController::class,'import'])->name('import');

Route::get('export', [ProductController::class, 'export'])->name('export'); 

Route::get('categoryexport', [CategoryController::class, 'export'])->name('categoryexport'); 

resources/views/admin/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Register') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('uesrs.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email"
                                    class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                        name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="password"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password"
                                        class="form-control @error('password') is-invalid @enderror" name="password"
                                        required autocomplete="new-password">

                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control"
                                        name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Role) }}</label>

                                <div class="col-md-6">
                                    <select name="role" id="role" aria-label="Default select example" class="form-control 
            @error('role') is-invalid @enderror ">
                                        @error('role')
                                            <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                        @enderror
                                        <div class="col-md-6">
                                            <option selected>Open this select menu</option>
                                            @foreach ($roles as $item)
                                                <option value="{{ $item->name }}">{{ $item->name }}</option>
                                            @endforeach
                                        </div>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <form action="{{ route('uesrs.update', $users->id) }}" method="POST" id="regform"
            enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="hidden" name="id" value="{{ $users->id }}">
        
            <div class="form-group">
                <label for="description">Name</label>
                <input type="text" name="name" value="{{ $users->name }}" class="form-control 
                        @error('name') is-invalid @enderror ">
                @error('name')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="image">Email</label>
                <input type="text" name="email" value="{{ $users->email }}" class="form-control
                        @error('email') is-invalid @enderror ">
                @error('email')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>

            {{--  <div class="form-group">

                <select name="Category" aria-label="Default select example" class="form-control
                        @error('Category') is-invalid @enderror ">
                    @error('Category_id')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
                    @foreach ($users as $user)
                        <option value="{{ $user->name }}" @if ($user->name == $product->Category) selected @endif>{{ $item->name }}</option>
                    @endforeach
                </select>
            </div>  --}}

            <div>
                <input type="submit" value="Update" class="btn btn-danger btn-block">
            </div>
        </form>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.master')

@section('title')
    <table class="table" id="product_table">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Role</th>
                <th scope="col">OPERATION</th>
            </tr>
        </thead>
 

    <tbody>
        @foreach ($users as $user)
            <tr>
                <td scope="col">{{ $user->id }}</td>
                <td scope="col">{{ $user->name }}</td>
                <td scope="col">{{ $user->email }}</td>
                <td scope="col"><label class="badge badge-success">{{$user->getRoleNames()}}</label></td>
                <td scope="col">
                    <form action="{{ route('uesrs.destroy', $user->id) }}" method="POST"
                        onsubmit="return confirm('Are you sure want to delete it')">
                        @csrf
                        @method('DELETE')
                        @hasanyrole('delete|admin')
                        <button type="submit" class="btn btn-danger" id="delete">DELETE</button>
                        @endhasanyrole
                       
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>

    
</table>

    <script type="text/javascript">
        $('#product_table').DataTable({
           
        });
    </script>
@endsection

resources/views/admin/show.blade.php
@extends('layouts.master')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show User</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('uesrs.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="container">
    <form>
        <div class="form-group">
            <label for="name"> Name</label>
            <input type="text"  value="{{$user->name}}" class="form-control">
        </div>
        <div class="form-group">
            <label for="name"> Email</label>
            <input type="text" value="{{$user->email}}" class="form-control">
        </div>
    </form>
</div>
@endsection