routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\JoinController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RelationController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::group(
    [
        'prefix' => 'store',
    ], function () {

        Route::resource('product', ProductController::class);

         Route::resource('category', CategoryController::class); 
        

        Route::resource('roles', RoleController::class);

        Route::resource('uesrs', UserController::class);

    });

Route::get('/', function () {
    return view('welcome');
});

Route::get('/join', [JoinController::class, 'show']);

Route::get('/relation', [RelationController::class, 'index'])->name('relation');

Route::get('about', [AboutController::class, 'about'])->name('about');

Route::get('contact', [AboutController::class, 'contact'])->name('contact');

Route::get('import-form', [ProductController::class, 'importForm'])->name('importForm');

Route::post('import',[ProductController::class,'import'])->name('import');

Route::get('export', [ProductController::class, 'export'])->name('export'); 

Route::get('categoryexport', [CategoryController::class, 'export'])->name('categoryexport'); 

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;

    use SoftDeletes;


     protected $fillable = [
        'name'
    ];
    
    
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Exports\CategoryExport;
use App\Models\Category;
use App\Repositories\category\CategoryRepositories;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\DataTables\Facades\DataTables;


class CategoryController extends Controller
{
    private $CategoryRepositories;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(CategoryRepositories $CategoryRepositories)
    {
        $this->CategoryRepositories = $CategoryRepositories;

        $this->middleware(['role_or_permission:admin']);
    }

    public function index(Request $request)
    {
        $data=$this->CategoryRepositories->all();

        return view('category.index',$data);
    }

    /**
     * Show the form for creating a new resource.
        *
        * @return \Illuminate\Http\Response
        */
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    public function store(Request $request)
    {
       $this->CategoryRepositories->store($request);
        return json_encode(array(
            "statusCode"=>200
        ));


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $data=$this->CategoryRepositories->show();
        
        return view('category.show',$data,['catogries' => Category::findOrFail($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('category.edit_category', ['categories'=>Category::FindOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categories=$this->CategoryRepositories->update($request,$id);
        return json_encode(array('statusCode'=>200));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {   
        $this->CategoryRepositories->delete($id);
        return redirect()->route('category.index');
    }   

    public function export()
    {
        return Excel::download(new CategoryExport, 'category.xlsx');
    }
}

resources/views/category/create.blade.php
@extends('layouts.master')

@section('title')

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
<form action="" id="createfrm">
    <div class="form-group">
        <input type="hidden" name="_token" id="csrf" value="{{ Session::token() }}">
        <label for="email">Name:</label>
        <input type="text" class="form-control" id="name" placeholder="Enter Name" name="name">
    </div>
    <button type="submit" class="btn btn-primary" id="butsave">Submit</button>
    </div>
</form>
   
    <script>
        $(document).ready(function() {

            $('#butsave').on('click', function() {
                var name = $('#name').val();
                if (name != "") {
                    /*  $("#butsave").attr("disabled", "disabled"); */
                    $.ajax({
                        url: "{{route('category.store')}}",
                        type: "POST",
                        data: {
                            _token: $("#csrf").val(),
                            type: 1,
                            name: name,
                        },
                        cache: false,
                        success: function(dataResult) {
                            console.log(dataResult);
                            var dataResult = JSON.parse(dataResult);
                            if (dataResult.statusCode == 200) {
                                window.location = "{{route('category.index')}}";
                            } else if (dataResult.statusCode == 201) {
                                alert("Error occured !");
                            }

                        }
                    });
                } else {
                    // alert('Please fill all the field !');
                }
            });
        });
    </script>


@endsection

resources/views/category/edit_category.blade.php
@extends('layouts.master')

@section('title')
    
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" id="name" name="name" value="{{ $categories->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <!-- -->
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button class="btn btn-primary" id="update_data" value="{{ $categories->id }}">Submit</button>
            </div>
        </div>
   
    {{-- </form> --}}
    <script>
        $(document).ready(function(){

    $(document).on("click", "#update_data", function() { 
        var url = "{{route('category.update',$categories->id)}}";
        var id= 
		$.ajax({
			url: url,
			type: "PATCH",
			cache: false,
			data:{
                _token:'{{ csrf_token() }}',
				type: 3,
				name: $('#name').val()
			},
			success: function(dataResult){
                dataResult = JSON.parse(dataResult);
             if(dataResult.statusCode)
             {
                window.location = "{{route('category.index')}}";
             }
             else{
                 alert("Internal Server Error");
             }
				
			}
		});
	}); 
});

    </script>
@endsection
     

resources/views/category/index.blade.php
@extends('layouts.master')

@section('content')
       
<div class="container">
    <a class="btn btn-success" href="{{ route('category.create') }}" id="createNewProduct"> Create New category</a>
    
    <table class="table" id="product_table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NAME</th>
                <th scope="col">Action</th>
            </tr>
        </thead>


        <tbody>
            @foreach ($categories as $categorie)
                <tr>
                    <td scope="col">{{ $categorie->id }}</td>
                    <td scope="col">{{ $categorie->name }}</td>
                    <td scope="col">
                        <form action="{{ route('category.destroy', $categorie->id) }}" method="POST"
                            onsubmit="return confirm('Are you sure want to delete it')">
                            @hasanyrole('delete|admin')
                            <a class="btn btn-info rounded-pill" href="{{ route('category.edit', $categorie->id) }}">EDIT</a>
                            @endhasanyrole

                            <a class="btn btn-warning rounded-pill"
                                href="{{ route('category.show', $categorie->id) }}">SHOW</a>

                            @csrf
                            @method('DELETE')
                            @hasanyrole('delete|admin')
                            <button type="submit" class="btn btn-danger rounded-pill" id="delete">DELETE</button>
                            @endhasanyrole

                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    
<script type="text/javascript">
  $(function () {
     
      $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
    $('#product_table').DataTable({

    });
     
    $('#createNewProduct').click(function () {
        $('#saveBtn').val("create-product");
        $('#id').val('');
        $('#productForm').trigger("reset");


    });
    
    $('body').on('click', '.editProduct', function () {
      var id = $(this).data('id');
      $.get("{{ route('category.index') }}" +'/' + id +'/edit', function (data) {
          $('#saveBtn').val("edit-user");
          $('#id').val(data.id);
          $('#name').val(data.name);
      })
   });
    
    $('#saveBtn').click(function (e) {
        e.preventDefault();
        $(this).html('Sending..');
    
        $.ajax({
          data: $('#productForm').serialize(),
          url: "{{ route('category.store') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {
              table.draw();
         
          },
          error: function (data) {
              console.log('Error:', data);
              $('#saveBtn').html('Save Changes');
          }
      });
    });
  });
</script>
@endsection
 

resources/views/category/join_table.blade.php
@extends('layouts.master')

@section('title')
    <table class="table">
        <thead>
            <tr>
                <th scope="col">categories.id</th>
                <th scope="col">NAME</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $row)
            <tr>
                <td scope="col">{{ $row->Category_id }}</td>
                <td scope="col">{{ $row->name }}</td>
            </tr>
            @endforeach
                
        </tbody>
    @endsection
</table>

resources/views/category/realtion.blade.php
@extends('layouts.master')

@section('title')
    <table class="table" id="relation">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">NAME</th>
                <th scope="col">member_id</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $row)
            <tr>
                <td scope="col">{{ $row->id }}</td>
                <td scope="col">{{ $row->name }}</td>
                <td scope="col">{{ $row->member_id }}</td>
            </tr>
            @endforeach
                
        </tbody>
    </table>
<script>
    $(document).ready( function () {
        $('#relation').DataTable();
    } );
</script>
    @endsection

resources/views/category/show.blade.php
@extends('layouts.master')

@section('title') 
        <form>
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"  value="{{$catogries->name}}" class="form-control">
            </div>
        </form>
@endsection